//
//  RestaurantListViewController.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NVActivityIndicatorView

protocol RestaurantListDisplayLogic: class {
  func displayActivityIndicator(_ show: Bool)
  func displayRestaurants(_ restaurants: [Restaurant])
  func displayError(_ title: String, _ message: String)
}

class RestaurantListViewController: UIViewController, RestaurantListDisplayLogic {
  var interactor: RestaurantListBusinessLogic?
  var router: (NSObjectProtocol & RestaurantListRoutingLogic & RestaurantListDataPassing)?

  @IBOutlet weak var tableView: UITableView!
  
  var restaurants = [Restaurant]()
  var activityData = ActivityData()
  var collectionId: Int = 0
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = RestaurantListInteractor()
    let presenter = RestaurantListPresenter()
    let router = RestaurantListRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    configureTableView()
    configureNavBar()
    configureActivityIndicator()
  }
  
  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    
    interactor?.getRestaurantsFromCollection(self.collectionId, 0)
  }
  
  func configureTableView() {
    self.tableView.dataSource = self
    self.tableView.delegate = self
  }
  
  func configureNavBar() {
    self.navigationController?.navigationBar.tintColor = .white
  }
  
  func configureActivityIndicator() {
    activityData = ActivityData(size: CGSize(width: 75, height: 75), message: nil, messageFont: nil, messageSpacing: nil, type: .ballPulse, color: .white, padding: 10, displayTimeThreshold: nil, minimumDisplayTime: 3, backgroundColor: nil, textColor: nil)
  }
  
  // MARK: RestaurantListDisplayLogic
  
  func displayActivityIndicator(_ show: Bool) {
    if show {
      NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)
    } else {
      NVActivityIndicatorPresenter.sharedInstance.stopAnimating()
    }
  }
  
  func displayRestaurants(_ restaurants: [Restaurant]) {
    self.restaurants = restaurants
    self.tableView.reloadData()
  }
  
  func displayError(_ title: String, _ message: String) {
    Alert.errorAlert(view: self, title: title, message: message)
  }
}

extension RestaurantListViewController: UITableViewDataSource, UITableViewDelegate {
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return self.restaurants.count
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    if let cell = tableView.dequeueReusableCell(withIdentifier: "restaurantCell", for: indexPath) as? RestaurantCell {
      cell.configureCell(self.restaurants[indexPath.row])
      return cell
    } else {
      return UITableViewCell()
    }
  }
  
  func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
    return 140
  }
}
