//
//  RestaurantListWorker.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RestaurantListWorker {
  let requestManager = RequestManager.sharedInstance
  let networkStatus = NetworkStatus.sharedInstance
  
  func getRestaurantsFromCollection(_ collectionId: Int, _ start: Int, completionHandler: @escaping (Any?, Error?) -> Void) {
    let params = [
      "entity_id": SessionManager.getCityId()!,
      "entity_type": "city",
      "count": 10,
      "start": start,
      "collection_id": collectionId
      ] as [String : Any]
    if networkStatus.isOnline {
      requestManager.makeRequest(params: params, type: .restaurantCollections) { (data, error) in
        completionHandler(data, error)
      }
    } else {
      
    }
  }
}
