//
//  SearchWorker.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker {
  let requestManager = RequestManager.sharedInstance
  let networkStatus = NetworkStatus.sharedInstance
  
  func getCity(_ q: String, completionHandler: @escaping (Any?, Error?) -> Void) {
    let params = ["q": q] as [String : Any]
    if networkStatus.isOnline {
      requestManager.makeRequest(params: params, type: .city) { (data, error) in
        completionHandler(data, error)
      }
    } else {
      
    }
  }
  
  func setCityId(_ id: String) {
    SessionManager.setCityId(id)
  }
}
