//
//  SearchPresenter.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
  func presentCities(_ cities: [City])
  func presentError(_ title: String, _ message: String)
  func presentActivityIndicator(_ show: Bool)
  func presentHomeViewController()
}

class SearchPresenter: SearchPresentationLogic {
  weak var viewController: SearchDisplayLogic?
  
  // MARK: SearchPresentationLogic
  
  func presentCities(_ cities: [City]) {
    viewController?.displayCities(cities)
  }
  
  func presentError(_ title: String, _ message: String) {
    viewController?.displayError(title, message)
  }
  
  func presentActivityIndicator(_ show: Bool) {
    viewController?.displayActivityIndicator(show)
  }
  
  func presentHomeViewController() {
    viewController?.displayHomeViewController()
  }
}
