//
//  HomePresenter.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/28/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
  func presentActivityIndicator(_ show: Bool)
  func presentCities(_ cities: [City])
  func presentError(_ title: String, _ message: String)
  func presentCollections(_ collections: [Collection])
}

class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?
  
  // MARK: HomePresentationLogic
  
  func presentActivityIndicator(_ show: Bool) {
    viewController?.displayActivityIndicator(show)
  }
  
  func presentCities(_ cities: [City]) {
    viewController?.displayCities(cities)
  }
  
  func presentError(_ title: String, _ message: String) {
    viewController?.displayError(title, message)
  }
  
  func presentCollections(_ collections: [Collection]) {
    viewController?.displayCollections(collections)
  }
}
