//
//  HomeRouter.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/28/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
  func routeToSearchController()
  func routeToCitySelection(_ cities: [Any])
  func routeToRestaurantListController(_ collectionId: Int, _ collectionName: String)
  func routeToRestaurantDetail(_ restaurant: Any)
}

protocol HomeDataPassing {
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
  func routeToSearchController() {
    if let searchVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SearchViewController") as? SearchViewController {
      searchVC.type = .city
      viewController?.navigationController?.pushViewController(searchVC, animated: true)
    }
  }
  
  func routeToCitySelection(_ cities: [Any]) {
    if let searchVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SearchViewController") as? SearchViewController {
      searchVC.type = .selection
      if let cities = cities as? [City] {
        searchVC.cities = cities
      }
      viewController?.navigationController?.pushViewController(searchVC, animated: true)
    }
  }
  
  func routeToRestaurantListController(_ collectionId: Int, _ collectionName: String) {
    if let restaurantVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RestaurantListViewController") as? RestaurantListViewController {
      restaurantVC.collectionId = collectionId
      restaurantVC.title = collectionName
      viewController?.navigationController?.pushViewController(restaurantVC, animated: true)
    }
  }
  
  func routeToRestaurantDetail(_ restaurant: Any) {
    if let detailVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RestaurantDetailViewController") as? RestaurantDetailViewController {
      if let restaurant = restaurant as? Restaurant {
        detailVC.restaurant = restaurant
      }
      viewController?.navigationController?.pushViewController(detailVC, animated: true)
    }
  }
}
