//
//  RestaurantDetailPresenter.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantDetailPresentationLogic {
  func presentActivityIndicator(_ show: Bool)
  func presentReviews(_ reviews: [Review])
  func presentError(_ title: String, _ message: String)
}

class RestaurantDetailPresenter: RestaurantDetailPresentationLogic {
  weak var viewController: RestaurantDetailDisplayLogic?
  
  // MARK: RestaurantDetailPresentationLogic
  
  func presentActivityIndicator(_ show: Bool) {
    viewController?.displayActivityIndicator(show)
  }
  
  func presentReviews(_ reviews: [Review]) {
    viewController?.displayReviews(reviews)
  }
  
  func presentError(_ title: String, _ message: String) {
    viewController?.displayError(title, message)
  }
}
