//
//  RestaurantDetailRouter.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RestaurantDetailRoutingLogic {
  func routeToRestaurantList()
}

protocol RestaurantDetailDataPassing {
  var dataStore: RestaurantDetailDataStore? { get }
}

class RestaurantDetailRouter: NSObject, RestaurantDetailRoutingLogic, RestaurantDetailDataPassing {
  weak var viewController: RestaurantDetailViewController?
  var dataStore: RestaurantDetailDataStore?
  
  // MARK: Routing
  
  func routeToRestaurantList() {
    viewController?.navigationController?.popViewController(animated: true)
  }
}
