//
//  RestaurantDetailWorker.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RestaurantDetailWorker {
  let requestManager = RequestManager.sharedInstance
  let networkStatus = NetworkStatus.sharedInstance
  
  func getReviews(_ resId: String, completionHandler: @escaping (Any?, Error?) -> Void) {
    let params = ["res_id": resId, "count": 10] as [String : Any]
    if networkStatus.isOnline {
      requestManager.makeRequest(params: params, type: .reviews) { (data, error) in
        completionHandler(data, nil)
      }
    } else {
      
    }
  }
}
