//
//  RestaurantDetailInteractor.swift
//  restaurant-app
//
//  Created by Jorge Luis Perales on 9/29/19.
//  Copyright (c) 2019 Jorge Luis Perales. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantDetailBusinessLogic {
  func getReviews(_ resId: String)
}

protocol RestaurantDetailDataStore {
  //var name: String { get set }
}

class RestaurantDetailInteractor: RestaurantDetailBusinessLogic, RestaurantDetailDataStore {
  var presenter: RestaurantDetailPresentationLogic?
  var worker = RestaurantDetailWorker()
  //var name: String = ""
  
  // MARK: RestaurantDetailBusinessLogic
  
  func getReviews(_ resId: String) {
    presenter?.presentActivityIndicator(true)
    worker.getReviews(resId, completionHandler: { (data, error) in
      self.presenter?.presentActivityIndicator(false)
      if error == nil {
        guard let reviews = data as? [Review] else { return }
        self.presenter?.presentReviews(reviews)
      } else {
        self.presenter?.presentError("Error", error!.localizedDescription)
      }
    })
  }
}
